stages:
  - build
  - push

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

before_script:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .

push:
  stage: push
  script:
    - docker push $DOCKER_IMAGE:latest