version: "3.8"

services:
  db:
    image: postgres:13
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  nextjs:
    image: node:20
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:your_db_password@db:5432/url_shortener
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: asdq
      GOOGLE_CLIENT_ID: "XXXXXXXXXXXXXXX"
      GOOGLE_CLIENT_SECRET: "XXXXXXXXXXXX"
      GITHUB_CLIENT_ID: "XXXXXXXXXXXXXXX"
      GITHUB_CLIENT_SECRET: "XXXXXXXXXXXX"
    depends_on:
      - db
    command: sh -c "chown -R node:node /app && npm install && npm run db:push && npm run build && npm run start"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
