import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Header from "~/components/layout/header";
import MovingBackground from "~/components/layout/background";
import Footer from "~/components/layout/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="min-h-screen bg-gray-900 text-white">
        <div className="bg-gradient-to-br from-gray-900 to-gray-800 transition-colors duration-300">
          <Header />
          <MovingBackground />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
